### ISSUE TITLE
depricated?

### ISSUE THREAD

**Issue by liljenstolpe** [securityrouter/changelog#1]
I noticed my license is now set to expire in a year, went looking and see that the project is EOL.  ;(  Are you going to release the code?

This was (is) the best OSS firewall router out there.  Please don't make me go back to pfsense or RYO...

Christopher

**Comment by eriklax** [comment]
Thanks for the kind word 👍 We'll however not release the code

**Comment by liljenstolpe** [comment]
Disappointing.  I hate to see this die.  if OSS, maybe it could live on.  Anyway - it's your call, obviously.

**Comment by netstx** [comment]
Id be willing to contribute if it's open source, and I think it'd make sense if you guys still charged a subscription for support if that fits your business goals. Like it was said, this is great software!
